extends:
 - ./lint/eslintrc-gjs.yml
 - ./lint/eslintrc-shell.yml
overrides:
  - files:
      - js/ui/init.js
      - js/dbusServices/**
      - subprojects/extensions-app/**
    parserOptions:
      sourceType: module
